name: E2E (Invoices)

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      # Server side (Express)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_BUCKET: reports
      API_PORT: 8787
      CORS_ORIGINS: http://localhost:5173
      NODE_ENV: test

      # Frontend (Vite)
      VITE_API_BASE_URL: http://localhost:8787
      VITE_SUPABASE_URL: http://localhost
      VITE_SUPABASE_ANON_KEY: dummy

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --no-audit

      - name: Run E2E (Invoices)
        run: npm run e2e:invoices

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/**
            cypress/videos/**
          if-no-files-found: ignore

