name: Promtool

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "prometheus-rule.yml"

jobs:
  promtool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Prometheus rules
        run: |
          docker run --rm -v "$PWD":/work -w /work prom/prometheus:latest \
            promtool check rules prometheus-rule.yml

